# Generated by Django 3.1.3 on 2022-01-18 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomUser', '0002_remove_user_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='student_auth',
            field=models.BooleanField(default=False),
        ),
    ]
