# Generated by Django 3.1.3 on 2022-01-20 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomUser', '0003_user_student_auth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='student_name',
            field=models.CharField(max_length=5),
        ),
    ]
