# Generated by Django 3.1.3 on 2022-02-26 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freeboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='delete_unavailable',
            field=models.CharField(max_length=2, null=True),
        ),
    ]
