# Generated by Django 3.1.3 on 2022-02-28 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryseat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='result',
            name='current',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='result',
            name='sequence_backup',
            field=models.TextField(blank=True),
        ),
    ]
