# Generated by Django 3.1.3 on 2022-03-07 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryseat', '0002_auto_20220228_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='day',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='receipt',
            name='month',
            field=models.CharField(max_length=2, null=True),
        ),
    ]
