# Generated by Django 3.1.3 on 2022-08-06 05:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('libraryseat', '0003_auto_20220307_2311'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt_Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee', models.CharField(max_length=2, null=True)),
                ('floor', models.CharField(max_length=2, null=True)),
                ('smoke', models.CharField(max_length=2, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Receipt_Student_author', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
