# Generated by Django 3.1.3 on 2022-08-17 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryseat', '0004_receipt_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt_student',
            name='student_number',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
