# Generated by Django 3.1.3 on 2021-04-06 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassA',
            list_display=('subject','professor'),
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('professor', models.CharField(max_length=200)),
                ('semester', models.CharField(max_length=200)),
                ('rate', models.CharField(max_length=200)),
            ],
        ),
    ]
