# Generated by Django 3.1.3 on 2021-04-08 02:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_classa'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassA_Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('semester', models.CharField(max_length=200)),
                ('rate', models.CharField(max_length=200)),
                ('classinfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.classa')),
            ],
        ),
    ]
