# Generated by Django 3.1.3 on 2021-04-08 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_classa_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='classa_post',
            name='create_date',
            field=models.DateTimeField(null=True),
        ),
    ]
