# Generated by Django 3.1.3 on 2021-04-08 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_classa_post_create_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='classa_post',
            name='subject',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
