# Generated by Django 3.1.3 on 2021-04-08 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0005_classa_post_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='classa_post',
            name='professor',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
