# Generated by Django 3.1.3 on 2021-11-20 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyroom', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserve',
            name='room',
            field=models.CharField(max_length=200),
        ),
    ]
