# Generated by Django 3.1.3 on 2021-12-02 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyroom', '0004_reserve_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserve',
            name='date',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
