# Generated by Django 3.1.3 on 2021-12-02 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyroom', '0005_reserve_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserve',
            name='date',
            field=models.IntegerField(max_length=10, null=True),
        ),
    ]
