# Generated by Django 3.1.3 on 2021-12-02 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyroom', '0006_auto_20211202_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserve',
            name='date',
            field=models.IntegerField(null=True),
        ),
    ]
